language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.4.5

before_install:
  - gem install bundler -v '< 2'
  - "rm gemfiles/*.lock"

install:
  - bundle _1.17.3_ install --retry=3 --jobs=3

script: "bundle exec rake clean test"
